(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (peep-dired highlight-global yasnippet-snippets yaml-mode xterm-color ws-butler writeroom-mode winum which-key wgrep web-mode web-beautify vterm volatile-highlights uuidgen use-package unfill treemacs-projectile treemacs-magit treemacs-evil toc-org terminal-here tagedit symon symbol-overlay string-inflection sql-indent spaceline-all-the-icons solarized-theme smex smeargle slim-mode shell-pop sass-mode restart-emacs ranger rainbow-delimiters pytest pyenv-mode pug-mode prettify-utils prettier-js popwin pippel pipenv pip-requirements persp-mode pcre2el password-generator overseer outshine orgit org-projectile org-present org-pomodoro org-mime org-download org-cliplink org-bullets org-brain open-junk-file ob-hy nameless mu4e-maildirs-extension mu4e-alert move-text mmm-mode markdown-toc magit-svn magit-gitflow macrostep lsp-ui lsp-treemacs lsp-python-ms lsp-haskell lorem-ipsum link-hint ivy-yasnippet ivy-xref ivy-rtags ivy-purpose ivy-hydra intero impatient-mode ibuffer-projectile hybrid-mode hy-mode hungry-delete hlint-refactor hl-todo hindent highlight-parentheses highlight-numbers highlight-indentation helm-make haskell-snippets graphviz-dot-mode google-translate google-c-style gitignore-templates gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-gutter-fringe git-gutter-fringe+ gh-md fuzzy font-lock+ flycheck-ycmd flycheck-rtags flycheck-pos-tip flycheck-package flycheck-haskell flx-ido faceup eyebrowse expand-region evil-visualstar evil-visual-mark-mode evil-unimpaired evil-textobj-line evil-surround evil-org evil-numbers evil-nerd-commenter evil-matchit evil-magit evil-lisp-state evil-lion evil-indent-plus evil-iedit-state evil-goggles evil-exchange evil-escape evil-ediff evil-cleverparens evil-args eshell-z esh-help emmet-mode elisp-slime-nav editorconfig dumb-jump dotenv-mode disaster diminish diff-hl devdocs define-word dante cython-mode csv-mode cquery cpp-auto-include counsel-projectile counsel-css company-ycmd company-web company-rtags company-lsp company-ghci company-ghc company-cabal company-c-headers company-anaconda cmm-mode clojure-snippets clean-aindent-mode clang-format cider-eval-sexp-fu cider ccls buttercup browse-at-remote blacken auto-yasnippet auto-highlight-symbol auto-dim-other-buffers auto-compile attrap all-the-icons-ivy all-the-icons-dired aggressive-indent ace-link ac-ispell))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
